name: ec2_deploy

on: 
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/my-app:latest

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_version: 1.5.0    
          
      - name: List files
        run: ls -la

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var "docker_image=${{ vars.DOCKERHUB_USERNAME }}/my-app:latest"

      - name: Terraform Apply
        run: terraform apply -auto-approve 